# This configuration is consumed only by the release workflow. It covers the
# dependency graphs shipped for every supported native target and asks
# cargo-about to fail rather than silently omit an unresolved license.
accepted = [
    "0BSD",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
    "GPL-3.0-or-later",
    "ISC",
    "LGPL-2.1-or-later",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc",
]
ignore-build-dependencies = false
ignore-dev-dependencies = false
ignore-transitive-dependencies = false

[ring]
accepted = ["OpenSSL"]

[unicode-ident]
accepted = ["Unicode-DFS-2016"]
