#!/usr/bin/env bash
# Generated by scripts/generate-localized-installers.py; do not edit manually.
# Locale: zh-CN
# This wrapper delegates all verification and installation work to the bundled
# scripts/install.sh. It is intentionally not a curl-pipe bootstrapper.

set -euo pipefail
IFS=$'\n\t'

readonly START_MESSAGE='正在启动 jgrep 安装程序…'
readonly ROOT_ERROR='未找到通用安装程序。请在已验证的 jgrep 安装程序包中运行此脚本。'

wrapper_directory="$(cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
installer_directory="$(cd -P -- "${wrapper_directory}/.." && pwd)"
repository_root="$(cd -P -- "${installer_directory}/.." && pwd)"
core_installer="${repository_root}/scripts/install.sh"

if [[ ! -f "${core_installer}" || -L "${core_installer}" ]]; then
    printf '%s\n' "${ROOT_ERROR}" >&2
    exit 1
fi

printf '%s\n' "${START_MESSAGE}" >&2
exec bash "${core_installer}" "$@"
