#!/usr/bin/env python3
"""Generate the localized jgrep installer wrappers.

The wrappers deliberately contain only presentation and deterministic discovery
of the bundled core installer.  Downloading, checksum verification, archive
handling, and installation stay in scripts/install.sh and scripts/install.ps1.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
import sys


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
INSTALLER_ROOT = REPOSITORY_ROOT / "installers"


# Keep this list aligned with the localized project and plugin READMEs.
LOCALES: dict[str, tuple[str, str]] = {
    "en": (
        "Starting the jgrep installer…",
        "The common installer was not found. Run this script from the verified jgrep installer bundle.",
    ),
    "ja": (
        "jgrep のインストーラーを開始します…",
        "共通インストーラーが見つかりません。検証済みの jgrep インストーラーバンドル内でこのスクリプトを実行してください。",
    ),
    "zh-CN": (
        "正在启动 jgrep 安装程序…",
        "未找到通用安装程序。请在已验证的 jgrep 安装程序包中运行此脚本。",
    ),
    "ko": (
        "jgrep 설치 프로그램을 시작합니다…",
        "공통 설치 프로그램을 찾을 수 없습니다. 검증된 jgrep 설치 프로그램 번들에서 이 스크립트를 실행하세요.",
    ),
    "es": (
        "Iniciando el instalador de jgrep…",
        "No se encontró el instalador común. Ejecute este script desde el paquete de instalación verificado de jgrep.",
    ),
    "de": (
        "Das Installationsprogramm für jgrep wird gestartet…",
        "Das gemeinsame Installationsprogramm wurde nicht gefunden. Führen Sie dieses Skript aus dem verifizierten jgrep-Installationspaket aus.",
    ),
    "ru": (
        "Запускается программа установки jgrep…",
        "Общий установщик не найден. Запустите этот скрипт из проверенного установочного пакета jgrep.",
    ),
    "fr": (
        "Démarrage du programme d’installation de jgrep…",
        "Le programme d’installation commun est introuvable. Exécutez ce script depuis le paquet d’installation jgrep vérifié.",
    ),
    "pt-BR": (
        "Iniciando o instalador do jgrep…",
        "O instalador comum não foi encontrado. Execute este script a partir do pacote de instalação verificado do jgrep.",
    ),
    "it": (
        "Avvio del programma di installazione di jgrep…",
        "Il programma di installazione comune non è stato trovato. Esegui questo script dal pacchetto di installazione verificato di jgrep.",
    ),
    "ar": (
        "يتم بدء مثبّت jgrep…",
        "لم يتم العثور على المثبّت المشترك. شغّل هذا البرنامج النصي من حزمة تثبيت jgrep التي تم التحقق منها.",
    ),
    "hi": (
        "jgrep इंस्टॉलर शुरू किया जा रहा है…",
        "सामान्य इंस्टॉलर नहीं मिला। इस स्क्रिप्ट को सत्यापित jgrep इंस्टॉलर बंडल से चलाएँ।",
    ),
}


def shell_quote(value: str) -> str:
    """Return a Bash single-quoted string without allowing template injection."""

    return "'" + value.replace("'", "'\"'\"'") + "'"


def powershell_quote(value: str) -> str:
    """Return a PowerShell single-quoted string without allowing template injection."""

    # PowerShell treats several typographic single quotation marks as string
    # delimiters too. Normalize them before applying its doubled-apostrophe
    # escape, otherwise French and similar messages can become invalid code.
    normalized = value.translate(
        str.maketrans({"\u2018": "'", "\u2019": "'", "\u201a": "'", "\u201b": "'"})
    )
    return "'" + normalized.replace("'", "''") + "'"


def render_shell(locale: str, start_message: str, root_error: str) -> bytes:
    return f'''#!/usr/bin/env bash
# Generated by scripts/generate-localized-installers.py; do not edit manually.
# Locale: {locale}
# This wrapper delegates all verification and installation work to the bundled
# scripts/install.sh. It is intentionally not a curl-pipe bootstrapper.

set -euo pipefail
IFS=$'\\n\\t'

readonly START_MESSAGE={shell_quote(start_message)}
readonly ROOT_ERROR={shell_quote(root_error)}

wrapper_directory="$(cd -P -- "$(dirname -- "${{BASH_SOURCE[0]}}")" && pwd)"
installer_directory="$(cd -P -- "${{wrapper_directory}}/.." && pwd)"
repository_root="$(cd -P -- "${{installer_directory}}/.." && pwd)"
core_installer="${{repository_root}}/scripts/install.sh"

if [[ ! -f "${{core_installer}}" || -L "${{core_installer}}" ]]; then
    printf '%s\\n' "${{ROOT_ERROR}}" >&2
    exit 1
fi

printf '%s\\n' "${{START_MESSAGE}}" >&2
exec bash "${{core_installer}}" "$@"
'''.encode("utf-8")


def render_powershell(locale: str, start_message: str, root_error: str) -> bytes:
    content = f'''# Generated by scripts/generate-localized-installers.py; do not edit manually.
# Locale: {locale}
# This wrapper delegates all verification and installation work to the bundled
# scripts/install.ps1. It is intentionally not an Invoke-Expression bootstrapper.

[CmdletBinding()]
param(
    [string]$Version,

    [string]$InstallDir,

    [string]$AssetDirectory,

    [string]$Repository,

    [string]$Target,

    [switch]$Force,

    [switch]$AddToPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$StartMessage = {powershell_quote(start_message)}
$RootError = {powershell_quote(root_error)}

if ([string]::IsNullOrWhiteSpace($PSScriptRoot)) {{
    throw $RootError
}}

try {{
    $wrapperDirectory = (Resolve-Path -LiteralPath $PSScriptRoot -ErrorAction Stop).Path
    # Split-Path cannot combine -LiteralPath and -Parent in Windows
    # PowerShell. Directory.GetParent retains literal-path semantics here.
    $installerDirectory = [System.IO.Directory]::GetParent($wrapperDirectory)
    if ($null -eq $installerDirectory) {{
        throw "installer bundle root is unavailable"
    }}
    $repositoryRoot = [System.IO.Directory]::GetParent($installerDirectory.FullName)
    if ($null -eq $repositoryRoot) {{
        throw "installer bundle root is unavailable"
    }}
    $repositoryRoot = (Resolve-Path -LiteralPath $repositoryRoot.FullName -ErrorAction Stop).Path
}}
catch {{
    throw "$RootError $($_.Exception.Message)"
}}

$coreInstaller = Join-Path $repositoryRoot "scripts/install.ps1"
if (-not (Test-Path -LiteralPath $coreInstaller -PathType Leaf)) {{
    throw $RootError
}}

$coreInstallerItem = Get-Item -LiteralPath $coreInstaller -Force -ErrorAction Stop
if (($coreInstallerItem.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0) {{
    throw $RootError
}}

Write-Host $StartMessage
& $coreInstaller @PSBoundParameters
'''
    # A BOM keeps Windows PowerShell 5.1 from interpreting localized text in
    # the current ANSI code page. Use CRLF for Windows-native script output.
    return b"\xef\xbb\xbf" + content.replace("\n", "\r\n").encode("utf-8")


def expected_files() -> dict[Path, tuple[bytes, int | None]]:
    files: dict[Path, tuple[bytes, int | None]] = {}
    for locale, (start_message, root_error) in LOCALES.items():
        locale_directory = INSTALLER_ROOT / locale
        files[locale_directory / "install.sh"] = (
            render_shell(locale, start_message, root_error),
            0o755,
        )
        files[locale_directory / "install.ps1"] = (
            render_powershell(locale, start_message, root_error),
            None,
        )
    return files


def is_current(path: Path, expected: bytes, mode: int | None) -> bool:
    try:
        if path.read_bytes() != expected:
            return False
        # Git records shell wrappers as executable, but Windows filesystems do
        # not expose POSIX execute bits through stat(). The generated bytes are
        # still checked there; enforce the mode only where it is meaningful.
        if (
            mode is not None
            and os.name != "nt"
            and path.stat().st_mode & 0o111 != 0o111
        ):
            return False
    except FileNotFoundError:
        return False
    return True


def write_files(files: dict[Path, tuple[bytes, int | None]]) -> None:
    for path, (content, mode) in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
        if mode is not None:
            path.chmod(mode)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate localized thin wrappers for the jgrep installers."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if a generated wrapper is missing, stale, or non-executable",
    )
    arguments = parser.parse_args()

    files = expected_files()
    stale = [
        path.relative_to(REPOSITORY_ROOT)
        for path, (content, mode) in files.items()
        if not is_current(path, content, mode)
    ]
    if arguments.check:
        if stale:
            for path in stale:
                print(f"stale localized installer: {path}", file=sys.stderr)
            print(
                "run scripts/generate-localized-installers.py to regenerate them",
                file=sys.stderr,
            )
            return 1
        return 0

    write_files(files)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
