# Generated by scripts/generate-localized-installers.py; do not edit manually.
# Locale: ko
# This wrapper delegates all verification and installation work to the bundled
# scripts/install.ps1. It is intentionally not an Invoke-Expression bootstrapper.

[CmdletBinding()]
param(
    [string]$Version,

    [string]$InstallDir,

    [string]$AssetDirectory,

    [string]$Repository,

    [string]$Target,

    [switch]$Force,

    [switch]$AddToPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$StartMessage = 'jgrep 설치 프로그램을 시작합니다…'
$RootError = '공통 설치 프로그램을 찾을 수 없습니다. 검증된 jgrep 설치 프로그램 번들에서 이 스크립트를 실행하세요.'

if ([string]::IsNullOrWhiteSpace($PSScriptRoot)) {
    throw $RootError
}

try {
    $wrapperDirectory = (Resolve-Path -LiteralPath $PSScriptRoot -ErrorAction Stop).Path
    # Split-Path cannot combine -LiteralPath and -Parent in Windows
    # PowerShell. Directory.GetParent retains literal-path semantics here.
    $installerDirectory = [System.IO.Directory]::GetParent($wrapperDirectory)
    if ($null -eq $installerDirectory) {
        throw "installer bundle root is unavailable"
    }
    $repositoryRoot = [System.IO.Directory]::GetParent($installerDirectory.FullName)
    if ($null -eq $repositoryRoot) {
        throw "installer bundle root is unavailable"
    }
    $repositoryRoot = (Resolve-Path -LiteralPath $repositoryRoot.FullName -ErrorAction Stop).Path
}
catch {
    throw "$RootError $($_.Exception.Message)"
}

$coreInstaller = Join-Path $repositoryRoot "scripts/install.ps1"
if (-not (Test-Path -LiteralPath $coreInstaller -PathType Leaf)) {
    throw $RootError
}

$coreInstallerItem = Get-Item -LiteralPath $coreInstaller -Force -ErrorAction Stop
if (($coreInstallerItem.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0) {
    throw $RootError
}

Write-Host $StartMessage
& $coreInstaller @PSBoundParameters
