#!/usr/bin/env bash
# Generated by scripts/generate-localized-installers.py; do not edit manually.
# Locale: ko
# This wrapper delegates all verification and installation work to the bundled
# scripts/install.sh. It is intentionally not a curl-pipe bootstrapper.

set -euo pipefail
IFS=$'\n\t'

readonly START_MESSAGE='jgrep 설치 프로그램을 시작합니다…'
readonly ROOT_ERROR='공통 설치 프로그램을 찾을 수 없습니다. 검증된 jgrep 설치 프로그램 번들에서 이 스크립트를 실행하세요.'

wrapper_directory="$(cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
installer_directory="$(cd -P -- "${wrapper_directory}/.." && pwd)"
repository_root="$(cd -P -- "${installer_directory}/.." && pwd)"
core_installer="${repository_root}/scripts/install.sh"

if [[ ! -f "${core_installer}" || -L "${core_installer}" ]]; then
    printf '%s\n' "${ROOT_ERROR}" >&2
    exit 1
fi

printf '%s\n' "${START_MESSAGE}" >&2
exec bash "${core_installer}" "$@"
