# Generated by scripts/generate-localized-installers.py; do not edit manually.
# Locale: de
# This wrapper delegates all verification and installation work to the bundled
# scripts/install.ps1. It is intentionally not an Invoke-Expression bootstrapper.

[CmdletBinding()]
param(
    [string]$Version,

    [string]$InstallDir,

    [string]$AssetDirectory,

    [string]$Repository,

    [string]$Target,

    [switch]$Force,

    [switch]$AddToPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$StartMessage = 'Das Installationsprogramm für localjev-grep wird gestartet…'
$RootError = 'Das gemeinsame Installationsprogramm wurde nicht gefunden. Führen Sie dieses Skript aus dem verifizierten localjev-grep-Installationspaket aus.'

if ([string]::IsNullOrWhiteSpace($PSScriptRoot)) {
    throw $RootError
}

try {
    $wrapperDirectory = (Resolve-Path -LiteralPath $PSScriptRoot -ErrorAction Stop).Path
    $installerDirectory = Split-Path -LiteralPath $wrapperDirectory -Parent
    $repositoryRoot = Split-Path -LiteralPath $installerDirectory -Parent
    if ([string]::IsNullOrWhiteSpace($repositoryRoot)) {
        throw "installer bundle root is unavailable"
    }
    $repositoryRoot = (Resolve-Path -LiteralPath $repositoryRoot -ErrorAction Stop).Path
}
catch {
    throw "$RootError $($_.Exception.Message)"
}

$coreInstaller = Join-Path $repositoryRoot "scripts/install.ps1"
if (-not (Test-Path -LiteralPath $coreInstaller -PathType Leaf)) {
    throw $RootError
}

$coreInstallerItem = Get-Item -LiteralPath $coreInstaller -Force -ErrorAction Stop
if (($coreInstallerItem.Attributes -band [System.IO.FileAttributes]::ReparsePoint) -ne 0) {
    throw $RootError
}

Write-Host $StartMessage
& $coreInstaller @PSBoundParameters
